USB_VID = 0x1209
USB_PID = 0x3501
USB_PRODUCT = "Thumby Color"
USB_MANUFACTURER = "TinyCircuits"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

CIRCUITPY_STAGE = 1
CIRCUITPY_AUDIOIO = 1
CIRCUITPY_AUDIOPWMIO = 1
CIRCUITPY_KEYPAD = 1
