USB_VID = 0x303A
USB_PID = 0x8371
USB_PRODUCT = "GLYPH S3"
USB_MANUFACTURER = "PCBCupid"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB
