name: Fetch Zephyr port deps

runs:
  using: composite
  steps:
    - name: Get Linux build dependencies
      if: runner.os == 'Linux'
      run: |
        echo "--- cpu model ---"
        grep "model name" /proc/cpuinfo | head -1
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev libudev-dev pkg-config mtools
        # We have to hold python3 so the following install works. See https://github.com/actions/runner-images/issues/13803
        sudo apt-mark hold python3
        sudo apt-get install -y libsdl2-dev:i386 libsdl2-image-dev:i386
        echo "PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}" >> $GITHUB_ENV
      shell: bash
    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: zephyr-config
        base-path: ports/zephyr-cp
        toolchains: arm-zephyr-eabi
    - name: Export cmake info
      run: west zephyr-export
      shell: bash
      working-directory: ports/zephyr-cp
