USB_VID = 0x1209
USB_PID = 0xD187
USB_PRODUCT = "uGameS3"
USB_MANUFACTURER = "deshipu"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_STAGE = 1
CIRCUITPY_KEYPAD = 1

CIRCUITPY_CANIO = 0
CIRCUITPY_DUALBANK = 0
CIRCUITPY_ESPCAMERA = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_ROTARYIO = 0

FROZEN_MPY_DIRS += $(TOP)/frozen/circuitpython-stage/ugame_s3
