#ifndef MICROPY_INCLUDED_RASPBERRYPI_BOARDS_PCBCUPID_Glyph_Mini_2040
#define MICROPY_INCLUDED_RASPBERRYPI_BOARDS_PCBCUPID_Glyph_Mini_2040

#define MICROPY_HW_BOARD_NAME "PCBCupid Glyph Mini 2040"
#define MICROPY_HW_MCU_NAME   "rp2040"

#define FLASH_SIZE            (8 * 1024 * 1024)
#define CIRCUITPY_INTERNAL_FLASH_FILESYSTEM_SIZE (7 * 1024 * 1024)

#define MICROPY_HW_LED_STATUS (&pin_GPIO16)

#endif
