USB_VID = 0x1209
USB_PID = 0x3500
USB_PRODUCT = "Thumby"
USB_MANUFACTURER = "TinyCircuits"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY_STAGE = 1
CIRCUITPY_AUDIOIO = 1
CIRCUITPY_AUDIOPWMIO = 1
CIRCUITPY_KEYPAD = 1

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_framebuf
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_SSD1306
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_DisplayIO_SSD1306
